### PR TITLE
Fix Emoji in HighlightedTextEditor

### PR DESCRIPTION
**Pull request by ceojosef**

### CODE REVIEW

**Comment by kyle-n** [comment]
Steps to reproduce bug this PR fixes:

- Create AppKit app with HLTE
- Delete all content in HLTE
- Paste an emoji (💩)
- Observe the emoji does not appear

**Comment by kyle-n** [comment]
I've updated this PR with a test for typing emoji into the AppKit editor. 

I've also used the steps to reproduce above in the UIKit editor and the bug exists there as well. Either one of us can fix it before merging this PR. I have some personal matters and won't be able to start working on this until Wednesday at the earliest.

**Comment by DerLobi** [comment]
Could we get this merged?
I noticed that it also affects highlighting matches if emojis are entered before the match, and emojis behind the match are not visible. This is in an iOS app.

The change proposed in this PR fixes the issue.
Let me know if I can help with resolving the merge conflicts or adding more test cases.

**Comment by kyle-n** [comment]
OK, GitHub is having issues allowing updates to PRs from people who did not create that PR, so I've taken the work on this branch and merged it into `main` using a separate branch #44. Thank you for noticing this bug, sorry it took so long to get fixed.

**Pull request closed without merging**
